"""initial_schema

Revision ID: 96263def757c
Revises: 
Create Date: 2026-10-05 19:31:34.387735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96263def757c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_name'), 'audit_logs', ['event_name'], unique=False)
    op.create_table('membership_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('max_vehicles', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plans_name'), 'membership_plans', ['name'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('max_discount_amount', sa.BigInteger(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promos_code'), 'promos', ['code'], unique=True)
    op.create_table('rentals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama_usaha', sa.String(), nullable=True),
    sa.Column('nib', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('kontak', sa.String(), nullable=True),
    sa.Column('status_verifikasi', sa.String(), nullable=True),
    sa.Column('membership_id', sa.String(length=36), nullable=True),
    sa.Column('payout_account', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rental_staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rental_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_staff_rental_id'), 'rental_staff', ['rental_id'], unique=False)
    op.create_index(op.f('ix_rental_staff_user_id'), 'rental_staff', ['user_id'], unique=True)
    op.create_table('user_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rental_id', sa.String(length=36), nullable=True),
    sa.Column('jenis', sa.String(), nullable=True),
    sa.Column('merk', sa.String(), nullable=True),
    sa.Column('tipe', sa.String(), nullable=True),
    sa.Column('plat_nomor', sa.String(), nullable=True),
    sa.Column('tarif_dasar', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plat_nomor')
    )
    op.create_index(op.f('ix_vehicles_rental_id'), 'vehicles', ['rental_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ktp_path', sa.String(), nullable=True),
    sa.Column('selfie_path', sa.String(), nullable=True),
    sa.Column('alasan', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_user_id'), 'verifications', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('rental_id', sa.String(length=36), nullable=True),
    sa.Column('judul', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.Column('biaya_tambahan', sa.BigInteger(), nullable=True),
    sa.Column('harga_all_in', sa.BigInteger(), nullable=True),
    sa.Column('status_publikasi', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_rental_id'), 'listings', ['rental_id'], unique=False)
    op.create_index(op.f('ix_listings_vehicle_id'), 'listings', ['vehicle_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('rental_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('tanggal_mulai', sa.Date(), nullable=True),
    sa.Column('tanggal_selesai', sa.Date(), nullable=True),
    sa.Column('hari', sa.Integer(), nullable=True),
    sa.Column('harga_per_hari', sa.BigInteger(), nullable=True),
    sa.Column('subtotal', sa.BigInteger(), nullable=True),
    sa.Column('diskon', sa.BigInteger(), nullable=True),
    sa.Column('promo_id', sa.String(length=36), nullable=True),
    sa.Column('total_nilai', sa.BigInteger(), nullable=True),
    sa.Column('dp', sa.BigInteger(), nullable=True),
    sa.Column('sisa', sa.BigInteger(), nullable=True),
    sa.Column('booking_state', sa.String(), nullable=True),
    sa.Column('escrow_state', sa.String(), nullable=True),
    sa.Column('alasan_batal', sa.String(), nullable=True),
    sa.Column('dibatalkan_oleh', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dp_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_listing_id'), 'bookings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_bookings_rental_id'), 'bookings', ['rental_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_vehicle_id'), 'bookings', ['vehicle_id'], unique=False)
    op.create_table('escrow_ledgers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('entry_type', sa.Enum('HOLD', 'RELEASE', 'REFUND', name='ledgerentrytype', native_enum=False), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_ledgers_booking_id'), 'escrow_ledgers', ['booking_id'], unique=False)
    op.create_table('handover_checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('bbm_persen', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('foto_urls', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'tipe', name='uq_booking_tipe')
    )
    op.create_index(op.f('ix_handover_checklists_booking_id'), 'handover_checklists', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('DP', 'PELUNASAN', name='paymenttype', native_enum=False), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BERHASIL', 'GAGAL', name='paymentstatus', native_enum=False), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_booking_id'), 'refunds', ['booking_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('author_role', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('komentar', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'author_role', name='uq_review_booking_role')
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_table('vehicle_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'tanggal', name='uq_vehicle_tanggal')
    )
    op.create_index(op.f('ix_vehicle_availability_tanggal'), 'vehicle_availability', ['tanggal'], unique=False)
    op.create_index(op.f('ix_vehicle_availability_vehicle_id'), 'vehicle_availability', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_availability_vehicle_id'), table_name='vehicle_availability')
    op.drop_index(op.f('ix_vehicle_availability_tanggal'), table_name='vehicle_availability')
    op.drop_table('vehicle_availability')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_refunds_booking_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_handover_checklists_booking_id'), table_name='handover_checklists')
    op.drop_table('handover_checklists')
    op.drop_index(op.f('ix_escrow_ledgers_booking_id'), table_name='escrow_ledgers')
    op.drop_table('escrow_ledgers')
    op.drop_index(op.f('ix_bookings_vehicle_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_rental_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_listing_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_listings_vehicle_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_rental_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_verifications_user_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_vehicles_rental_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_rental_staff_user_id'), table_name='rental_staff')
    op.drop_index(op.f('ix_rental_staff_rental_id'), table_name='rental_staff')
    op.drop_table('rental_staff')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_promos_code'), table_name='promos')
    op.drop_table('promos')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_membership_plans_name'), table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index(op.f('ix_audit_logs_event_name'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
